apiVersion: v1
kind: ConfigMap
metadata:
  name: cmap
  labels:
    app: sosmed
data:
  DB_HOST: dbpaus.cyvxmusxt9s8.ap-southeast-2.rds.amazonaws.com #config file environment
  DB_USER: admin
  DB_PASS: Cilsy2023
  DB_NAME: dbpaus